spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://10.71.202.29:1433/microservice-spirit;instance=SQL2008
    username: sa
    password: iamdante
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: dante
    password: 123456
    virtual-host: /project-config