spring:
  redis:
    host: ${redis.host:localhost}
    port: ${redis.host:6379}
  rabbitmq: 
    host: ${rabbitmq.host:localhost}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.username:dante}
    password: ${rabbitmq.password:123456}
    virtual-host: /project-config
zuul:
  routes:
    project-sysmgr-ui:
      path: /sysmgr/**
      sensitive-headers: null