spring:
  redis:
    host: ${redis.host:localhost}
    port: ${redis.host:6379}
  rabbitmq: 
    host: ${rabbitmq.host:localhost}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.username:dante}
    password: ${rabbitmq.password:123456}
    virtual-host: /project-config
  sleuth:
    sampler:
      percentage: ${config.sampler:0.3}
  zipkin:
    base-url: ${zipkin.server:http://localhost:9411/}
zuul:
  routes:
    project-sysmgr-ui:
      path: /sysmgr/**
    project-syslog-ui:
      path: /syslog/**
spirit:
  kaptcha: true
  safeCheck: true
  ldapurl: '{cipher}AQB+ogHC4ThGR7F+waKvPWETYVivLv0mh0/riMwBj3E9FVDVGHKwKQOXy9wEL/52l3FOvRuhjPYzDPPjP/txBFQm7QecXhqKPaYNeJqXiT2gfx5JFJGr/fD/ilX8XDf9cDF1SfOISkchDJcHNL3F2Y2b3HXhO+0JUOogf2LH3UXYH/nTJ9ro/IbuiH5W6FOY+L/wcAJIMrSZKC9TNPGUWTDB057P+71K3u2t4XZnueZeCHzNq9TUMTvQ4sF0J7R2XZKIURQsamgQMeMD0ifFtGQW2jfBPyFt+8O0piy0/ExrLETok9Lu2+l4Na/CVKs6TU/UwgSGYqGqNNUhcCVLs6ITD3Kl1Ilup24UcnitVkiUONH1Fgf6mqgEQtmqjxPIrIHBDdfnuRy47ccmgoJ6KVFY'