spring:
  redis:
    host: localhost
    port: 6379
  rabbitmq: 
    host: localhost
    port: 5672
    username: dante
    password: 123456
    virtual-host: /project-config
zuul:
  routes:
    project-sysmgr-ui:
      path: /sysmgr/**
      sensitive-headers: null