spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/dante/Documents/Project/spring/microservice-spirit/project-config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: dante
    password: 123456
    virtual-host: /project-config