spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dante7qx/microservice-spirit
          search-paths:
            - project-config-repo
#          username: dante7qx
#          password: Dante2012
  rabbitmq:
    host: localhost
    port: 5672
    username: 
    password: 
    virtual-host: /project-config
