spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dante7qx/microservice-spirit
          search-paths:
            - project-config-repo
  rabbitmq:
    host: ${rabbitmq.host:localhost}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.username:dante}
    password: ${rabbitmq.password:123456}
    virtual-host: /project-config
encrypt:
  keyStore:
    location: classpath:server.jks 
    password: 1234@@qwer       
    alias: SpiritKey
    secret: 12,qw,as